# Generated by Django 6.1 on 2026-09-30 22:22

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'verbose_name': 'autor',
                'verbose_name_plural': 'autores',
                'db_table': 'libros_autor',
                'ordering': ('nombre',),
            },
        ),
        migrations.CreateModel(
            name='CategoriaLibro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=90, unique=True)),
            ],
            options={
                'verbose_name': 'categoría de libro',
                'verbose_name_plural': 'categorías de libros',
                'db_table': 'libros_categoria',
                'ordering': ('nombre',),
            },
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=180, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('anio', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(2100)], verbose_name='año')),
                ('paginas', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='páginas')),
                ('calificacion', models.DecimalField(decimal_places=1, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='calificación')),
                ('disponible', models.BooleanField(db_index=True, default=True)),
                ('destacado', models.BooleanField(default=False)),
                ('imagen', models.CharField(default='portada_general.png', max_length=255)),
                ('sinopsis', models.TextField()),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='libros', to='librosApp.autor')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='libros', to='librosApp.categorialibro')),
            ],
            options={
                'verbose_name': 'libro',
                'verbose_name_plural': 'libros',
                'db_table': 'libros_libro',
                'ordering': ('titulo',),
            },
        ),
        migrations.CreateModel(
            name='ReservaLibro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_retiro', models.DateField()),
                ('fecha_devolucion_prevista', models.DateField()),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmada', 'Confirmada'), ('cancelada', 'Cancelada'), ('completada', 'Completada')], db_index=True, default='pendiente', max_length=12)),
                ('observaciones', models.CharField(blank=True, max_length=300)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('actualizada_en', models.DateTimeField(auto_now=True)),
                ('libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='librosApp.libro')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas_libros', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'reserva de libro',
                'verbose_name_plural': 'reservas de libros',
                'db_table': 'libros_reserva',
                'ordering': ('-creada_en',),
            },
        ),
    ]
