# Generated by Django 6.1 on 2026-09-30 22:22

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaPelicula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=90, unique=True)),
            ],
            options={
                'verbose_name': 'categoría de película',
                'verbose_name_plural': 'categorías de películas',
                'db_table': 'peliculas_categoria',
                'ordering': ('nombre',),
            },
        ),
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=180, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('director', models.CharField(max_length=150)),
                ('anio', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1888), django.core.validators.MaxValueValidator(2100)], verbose_name='año')),
                ('duracion_minutos', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('calificacion', models.DecimalField(decimal_places=1, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='calificación')),
                ('destacada', models.BooleanField(default=False)),
                ('imagen', models.CharField(default='portada_general.png', max_length=255)),
                ('sinopsis', models.TextField()),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='peliculas', to='peliculasApp.categoriapelicula')),
            ],
            options={
                'verbose_name': 'película',
                'verbose_name_plural': 'películas',
                'db_table': 'peliculas_pelicula',
                'ordering': ('titulo',),
            },
        ),
        migrations.CreateModel(
            name='ReservaPelicula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_funcion', models.DateTimeField(verbose_name='fecha y hora de la función')),
                ('cantidad_entradas', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmada', 'Confirmada'), ('cancelada', 'Cancelada'), ('completada', 'Completada')], db_index=True, default='pendiente', max_length=12)),
                ('observaciones', models.CharField(blank=True, max_length=300)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('actualizada_en', models.DateTimeField(auto_now=True)),
                ('pelicula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='peliculasApp.pelicula')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas_peliculas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'reserva de película',
                'verbose_name_plural': 'reservas de películas',
                'db_table': 'peliculas_reserva',
                'ordering': ('-creada_en',),
            },
        ),
    ]
